# Production deployment workflow
# Triggers on pushes to 'production' branch for optimized live deployment

name: Deploy to Firebase Hosting Production
on:
  push:
    branches:
      - production
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
            
      # Simple, effective npm install optimization
      - name: Install dependencies
        run: |
          npm config set progress false
          npm config set audit false
          npm config set fund false
          npm ci --prefer-offline --no-audit --no-fund --silent
            
      - name: Build project
        run: npm run build:production
      
      - name: Deploy to Firebase Hosting (Production)
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EDGEVIDEO_AI_8753A }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $GITHUB_WORKSPACE/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-service-account.json
          npx firebase-tools deploy --only hosting:edgevideo-production --project edgevideo-ai-8753a --non-interactive
